name: my-lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Lint with flake8
        run: |
          poetry run flake8 brain_games
        
        
