name: my-lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    streategy:
      matrix:
        python-verison: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python #{{ matrix.python-verison }}
          uses: action/setup-python@v2
          with:
            python-verison: ${{ matrix.python-verison }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          poetry run pytest
          poetry run flake8 brain_games
      - name: Test &Publish code coverage
        uses: ppambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: poetry run pytest --cov=brain_games --cov-report xml
          debug: true
        
        
